name: Build

on:
  push:
    branches: [ master ]
    tags: [ '*' ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Configure
      run: cmake -DCMAKE_MSVC_RUNTIME_LIBRARY=MultiThreaded -DCMAKE_C_FLAGS_RELEASE="/MT /O2" -B ${{github.workspace}}/build
    - name: Build
      run: cmake --build ${{github.workspace}}/build --config Release -j
    - name: Archive
      if: ${{ github.ref_type == 'tag' }}
      uses: actions/upload-artifact@v4
      with:
        name: PhotoTime-${{github.ref_name}}
        path: build/Release/PhotoTime.exe
        retention-days: 1
